add top songs command
Deseteral/lebkuchen-fm pull request #178
Opened 2022-10-14 16:11 UTC by gorzalczany

### why
issue https://github.com/Deseteral/lebkuchen-fm/issues/37

### sample output
```
#    grano   tytuł
------------------------
1    3       Kraftwerk - Showroom Dummies
2    2       KRAFTWERK - THE MODEL
3    1       Depeche Mode - Enjoy The Silence (Official Video)
4    1       a-ha - Take On Me (Official Video) [Remastered in …
5    1       Pet Shop Boys - West End Girls (Official Video) [H…
6    1       The Human League - Love Action (I Believe In Love)
7    1       New Order - Blue Monday 12 inch (HD)
8    1       Pet Shop Boys-west end girls official video.
9    1       Vintage French Minimal Synthpop (1980)
10   1       Eurythmics, Annie Lennox, Dave Stewart - Sweet Dre…
```

2022-10-15 12:14 UTC, Deseteral requested changes

2022-10-15 12:14 UTC, Deseteral commented on packages/service/src/domain/songs/songs-repository.ts
> +  getOrderedByTimesPlayedDesc(limit: number): Promise<Song[]> {
```suggestion
  findAllOrderedByTimesPlayedDesc(limit: number = 0): Promise<Song[]> {
```

2022-10-15 12:14 UTC, Deseteral commented on packages/service/src/domain/songs/songs-service.ts
> +  async getTop(limit: number): Promise<Song[]> {
```suggestion
  async getWithHighestPlayCount(limit: number): Promise<Song[]> {
```
albo coś podobnego. `getTop` jest IMO zbyt lakoniczne.

2022-10-15 12:14 UTC, Deseteral commented on packages/service/src/domain/commands/processors/song-top-command.ts
> +        return place + played + title.replace(/(.{50})..+/, '$1…');
Ten replace też zrób wyżej, tam gdzie definiujesz title. Dodatkowo - jesteś pewien że on działa? Z tym `$1`?

2022-10-29 16:57 UTC, gorzalczany commented on packages/service/src/domain/commands/processors/song-top-command.ts
> +        return place + played + title.replace(/(.{50})..+/, '$1…');
zgodnie z ustaleniami z innego PRa pozbyliśmy się regexa na rzecz rozszerzenia String

2022-10-29 17:00 UTC, Deseteral approved these changes

2022-10-29 17:19 UTC, merged