Windows
Deseteral/lebkuchen-fm pull request #242
Opened 2024-03-01 19:33 UTC by mswiechowicz

2024-08-13 19:29 UTC, Deseteral requested changes

2024-10-08 17:28 UTC, mswiechowicz commented on packages/client-beta/src/views/Login/Login.tsx
> +    userLogin('lebkuchen', password)
removed whole file

2024-10-08 17:28 UTC, mswiechowicz commented on packages/client-beta/src/views/Login/Login.tsx
> +  const username = localStorage.getItem('lebkuchenfm-username');
removed whole file

2024-10-08 17:28 UTC, mswiechowicz commented on packages/client-beta/src/apps/Soundboard/Soundboard.tsx
> +        imgSrc="https://cdn2.iconfinder.com/data/icons/gadgets-and-devices/48/60-512.png"
Changes to free icon from font awesome

2024-10-10 14:05 UTC, Deseteral approved these changes

2024-10-11 07:30 UTC, merged