[beta] add basic user management to beta
Deseteral/lebkuchen-fm pull request #308
Opened 2024-12-14 01:20 UTC by gorzalczany

This PR contains both: backend and frontend changes 😱 
![Screenshot 2024-12-14 at 02 19 48](https://github.com/user-attachments/assets/0a7e6437-60e3-4269-a021-a7bd746e475e)

2025-01-24 20:12 UTC, kstodolak requested changes

2025-01-24 20:12 UTC, kstodolak commented on client/src/apps/Users/Users.module.css
> +table {
W ten sposób w stylach komponentu zmieniasz globalne style dla tagów tabeli. Jeśli rzeczywiście chciałeś to zrobić to nie powinieneś robić tego tutaj. Zamiast tego:
1. W pliku `src/styles.css`
2. Lub jeszcze lepiej może zrobić reużywalny komponent tabeli.

W przeciwnym wypadku w tym miejscu trzymałbym się klas, które potem przy budowaniu będą miały scope modułu.

2025-01-24 20:12 UTC, kstodolak commented on client/src/apps/Users/Users.module.css
> +  background: silver;
1. `thead` i tak semantycznie powinien być w `table`
2. Nie wiem czy w tym wypadku nie wystarczyłoby, żebyś te style ustawił osobno po prostu dla `thead` i dla `tbody`. Jeśli elementy wewnątrz nie nadpiszą tych styli to i tak odziedziczą je od rodzica. Chyba nawet z tym sticky powinno na luzie zadziałać. Wtedy cały element się przyklei (ale to już tak z głowy mówię :D)

2025-01-24 20:12 UTC, kstodolak commented on client/src/apps/Users/Users.module.css
> +  color: red;
Takie kolory jeśli widzisz opcję reużywalności to można dodać jako zmienną CSS w pliku `src/styles.css`

2025-01-24 20:14 UTC, Deseteral requested changes

2025-01-24 20:14 UTC, Deseteral commented on service/src/main/kotlin/xyz/lebkuchenfm/external/storage/mongo/repositories/UsersMongoRepository.kt
> +            .map { it.toDomain() }.toList()
[style] Move `toList` to new line maybe?

2025-01-24 20:14 UTC, Deseteral commented on service/src/main/kotlin/xyz/lebkuchenfm/api/users/UsersEndpoint.kt
> +            print(formParameters.names())
Remove `print`

2025-01-24 20:14 UTC, Deseteral commented on service/src/main/kotlin/xyz/lebkuchenfm/api/users/UsersEndpoint.kt
> +                call.respond(HttpStatusCode.BadRequest, "Missing required field: username.")
We should respond with Problem in this case.

2025-01-24 20:14 UTC, Deseteral commented on service/src/main/kotlin/xyz/lebkuchenfm/api/users/UsersEndpoint.kt
> +                    call.respond(
We should respond with Problem in this case.

2025-03-02 13:13 UTC, Deseteral commented on client/src/apps/Users/Users.tsx
> +      <td>{`${new Date(user.lastLoggedIn).toLocaleString('pl-PL')}`}</td>
I'm not too fond of hardcoding `pl-PL` here.

2025-03-02 13:13 UTC, Deseteral commented on client/src/services/users-service.ts
> +    throw new Error(await response.text());
When the response is not in 2xx family its body will contain JSON with Problem object. So using `.text()` here is kind of useless. In my opinion we should propagate the Problem object up to the view layer so that we could render the error message to the user. Sad that we cannot specify the rejection type of a Promise.

TLDR
```suggestion
    throw new Error(await response.json());
```

2025-03-02 13:13 UTC, Deseteral commented on client/src/apps/Users/Users.tsx
> +      .then((user) => setError(JSON.stringify(user)))
I don't understand this - `setError` for success branch of the Promise? Why? Why with the JSON? Is that the leftover from debugging?

2025-03-02 19:04 UTC, gorzalczany commented on client/src/apps/Users/Users.tsx
> +      .then((user) => setError(JSON.stringify(user)))
Kind of, I copied setError from sound management. We just use it as visible output. It should be replaced system wise with something prettier. Maybe something  like [angular notification](https://www.telerik.com/kendo-angular-ui/components/notification#angular-notification-example)

2025-03-02 19:06 UTC, gorzalczany commented on client/src/apps/Users/Users.tsx
> +      <td>{`${new Date(user.lastLoggedIn).toLocaleString('pl-PL')}`}</td>
true

2025-03-03 20:05 UTC, Deseteral submitted a review, later dismissed

2025-03-18 19:05 UTC, Deseteral approved these changes

2025-03-18 19:06 UTC, kstodolak approved these changes

2025-03-18 19:08 UTC, merged